### ISSUE TITLE
ModuleNotFoundError: No module named 'google.cloud.dataproc_v1.gapic'

### ISSUE THREAD

**Issue by sneha2701** [googleapis/python-dataproc#421]
code:

import base64
from google.cloud import dataproc_v1
from google.cloud.dataproc_v1.gapic.transports import cluster_controller_grpc_transport

def hello_pubsub(event, context):
pubsub_message = base64.b64decode(event['data']).decode('utf-8')
print(pubsub_message)
print("inside function")
#region = "us-central1"
transport = cluster_controller_grpc_transport.ClusterControllerGrpcTransport(
address='us-central1-dataproc.googleapis.com:443')
client = dataproc_v1.ClusterControllerClient(transport)
#region = "us-central1"
print("Client value is", client)
# Initialize request argument(s)
request = dataproc_v1.DeleteWorkflowTemplateRequest(
name="projects/xyz/regions/us-central1/workflowTemplates/template-123",
)
# Make the request
if client.delete_workflow_template(request=request) == 1:
print("Client")
else:
print("Not deleted")

requirement.txt

google-cloud
google-cloud-dataproc
google-cloud-ndb
grpcio

**Comment by jjkoh95** [comment]
I faced this issue awhile ago [here](https://gist.github.com/jjkoh95/70e0f3a351d7f8480455aaa4996f5471), and I believe the `gapic` module might be deprecated and removed

This is the solution that I found:
```python
    client = dataproc_v1.ClusterControllerClient(
        client_options={"api_endpoint": "us-central1-dataproc.googleapis.com:443"},
    )
```

**Comment by namdyny** [comment]
I faced similar issue as well. Since #71, ClusterControllerGrpcTransport is being moved to `google/cloud/dataproc_v1/services/cluster_controller/transports/grpc.py`, which is imported by `google/cloud/dataproc_v1/services/cluster_controller/transports/__init__.py`. Following this path, you should be able to import ClusterControllerGrpcTransport.
Note: the namespace for ClusterControllerGrpcTransport is not mentioned in `google/cloud/dataproc_v1/__init__.py`

**Comment by parthea** [comment]
Closing as obsolete as the `gapic` module was removed in https://github.com/googleapis/python-dataproc/pull/71
